version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myhotel
    ports:
      - "3308:3306"
    volumes:
        - ./db:/docker-entrypoint-initdb.d