version: '3'

services:

  db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myhotel
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    
  adminer:
    image: adminer
    restart: always
    ports: 
      - "8080:8080"